### ISSUE TITLE
bug for character/string types

### ISSUE THREAD

**Issue by hung18052001** [frankxayachack/LaoWordSegmentation#1]
I try to compile the code, and get this feature
![image](https://user-images.githubusercontent.com/62647817/134814509-e9274d9d-93d7-4cb1-933e-015ecf18e8dc.png)
![image](https://user-images.githubusercontent.com/62647817/134814549-978624b8-04b9-4b4f-bf8b-e91cc1f512d9.png)
 if you see the image, you can recognize that when compiling java understand Lao character as a string, but in java string must be contained in " ". So how can I fix this problem. Thanks!

**Comment by hung18052001** [comment]
> I try to compile the code, and get this feature
> ![image](https://user-images.githubusercontent.com/62647817/134814509-e9274d9d-93d7-4cb1-933e-015ecf18e8dc.png)
> ![image](https://user-images.githubusercontent.com/62647817/134814549-978624b8-04b9-4b4f-bf8b-e91cc1f512d9.png)
> if you see the image, you can recognize that when compiling java understand Lao character as a string, but in java string must be contained in " ". So how can I fix this problem. Thanks!

**Comment by frankxayachack** [comment]
please do the Pull Request
